'''Tourist recommendation system'''
for i in range(3):
    print("*"*40)
print("     WELCOME TO MP TOURIST GUIDE")

for i in range(3):
    print("*" * 40)

print("Choose Your Destination")
print("1. Indore")
print("2. Bhopal")
print("3. Dhar")
print("4. Ujjain")
print()

location=int(input("Enter Your Destination:"))
match (location):
    case 1:
        print("\nChoose Budget")
        print("1. Under ₹5000")
        print("2. ₹5000 OR ABOVE ")
        budget=int(input("Enter your choice:"))
        print("want room or not?")
        room=input("yes/no").lower()

        print("")
        print("\nHow many days will you stay?")
        print("1")
        print("2")
        print("3")
        print("4")
        print("5")
        days = int(input("Enter number of days: "))
        print("")
        print("Chosse the transport type ")
        print("\nChoose Transport")
        print("1. Bus")
        print("2. Train")
        print("3. Bike")
        print("4. Car")
        transport = int(input("Enter your choice: "))
        if budget==1  and room=="yes" and transport==1:
            if days==1:
                print("\n1 DAY TRIP")
                print("Places to Visit:")
                print("1. Rajwada Palace")
                print("2. Lal Bagh Palace")
                print("3. Kanch Mandir")
                print("4. Sarafa Bazaar (Night Food Market)")
                print("Room: Not Required")
                print("Food: Rs.300 - Rs.500")
                print("Transport: Rs.200 - Rs.400")
                print("Estimated Budget: Rs.700 - Rs.1000")
            elif days==2:
                print("\n2 DAY TRIP")
                print("Day 1:")
                print("- Rajwada Palace")
                print("- Lal Bagh Palace")
                print("- Kanch Mandir")
                print("- Sarafa Bazaar")
                print("Day 2:")
                print("- Patalpani Waterfall")
                print("- Tincha Falls")
                print("- Chappan Dukan")
                print("Food: Rs.600 - Rs.800")
                print("Transport: Rs.500 - Rs.700")
                print("Estimated Budget: Rs.2500 - Rs3500")
            else:
                if days >= 3:
                    print("\n3 DAY TRIP")
                    print("Day 1:")
                    print("- Rajwada Palace")
                    print("- Lal Bagh Palace")
                    print("- Sarafa Bazaar")

                    print("Day 2:")
                    print("- Patalpani Waterfall")
                    print("- Ralamandal Wildlife Sanctuary")

                    print("Day 3:")
                    print("- Ujjain")
                    print("- Mahakaleshwar Temple")
                    print("- Ram Ghat")
                    print("Food: Rs.900 - Rs.1200")
                    print("Transport: Rs.800 - Rs.1200")
                    print("Estimated Budget: Rs.4500")
        if budget==1  and room=="no" and transport==1:
            if days==1:
                print("\n1 DAY TRIP")
                print("Places to Visit:")
                print("1. Rajwada Palace")
                print("2. Lal Bagh Palace")
                print("3. Kanch Mandir")
                print("4. Sarafa Bazaar (Night Food Market)")
                print("Room: Not Required")
                print("Food: Rs.300 - Rs.500")
                print("Transport: Rs.200 - Rs.400")
                print("Estimated Budget: Rs.700 - Rs.1000")
            elif days==2:
                print("\n2 DAY TRIP")
                print("Day 1:")
                print("- Rajwada Palace")
                print("- Lal Bagh Palace")
                print("- Kanch Mandir")
                print("- Sarafa Bazaar")
                print("Day 2:")
                print("- Patalpani Waterfall")
                print("- Tincha Falls")
                print("- Chappan Dukan")
                print("Food: Rs.600 - Rs.800")
                print("Transport: Rs.500 - Rs.700")
                print("Estimated Budget: Rs.2500 - Rs3500")
            else:
                if days >= 3:
                    print("\n3 DAY TRIP")
                    print("Day 1:")
                    print("- Rajwada Palace")
                    print("- Lal Bagh Palace")
                    print("- Sarafa Bazaar")

                    print("Day 2:")
                    print("- Patalpani Waterfall")
                    print("- Ralamandal Wildlife Sanctuary")

                    print("Day 3:")
                    print("- Ujjain")
                    print("- Mahakaleshwar Temple")
                    print("- Ram Ghat")
                    print("Food: Rs.900 - Rs.1200")
                    print("Transport: Rs.800 - Rs.1200")
                    print("Estimated Budget: Rs.4500")